# Site settings
title: CodePlus
email: yuki.n.0918@gmail.com
description: ""
baseurl: ""
url: "http://code-plus.jp"
username: yukinaka
twitter: yuki_naka18

# Build settings
markdown: kramdown
permalink: /:title/
paginate: 10
paginate_path: "/page:num"
